Repository QuasarApp/CQtDeployer, pull requests merged in 2021-01, with the labels that each got.

#483 Fixed search for libraries in the system environment during testing.
  Deploy/envirement.cpp
  Deploy/ignorerule.cpp
  UnitTests/modulesqt513.cpp
  UnitTests/testutils.cpp
  UnitTests/tst_deploytest.cpp
Labels: Bug, Windows

#482 Use STL header <set> instead of the internal header <bits/stl_set.h>
  Deploy/pe_type.cpp
Labels: Bug, Windows

#487 New option "runScript"
  Deploy/Distributions/Templates/qif/packages/default/meta/installscript.qs
  Deploy/configparser.cpp
  Deploy/configparser.h
  Deploy/deployconfig.cpp
  Deploy/deployconfig.h
  Deploy/deploycore.cpp
  Deploy/distromodule.cpp
  Deploy/distromodule.h
  Deploy/metafilemanager.cpp
  Deploy/metafilemanager.h
  UnitTests/modulesqt513.cpp
  UnitTests/res.qrc
  UnitTests/testRes/customRunScript.sh
  UnitTests/tst_deploytest.cpp
  docs/en/Options.md
  docs/ru/Options.md
Labels: Doc, Enhancement, Linux, Windows

#488 Added documentation for extraData option.
  docs/en/ExtraFiles.md
  docs/en/Guide.md
  docs/en/Home.md
  docs/ru/ExtraFiles.md
  docs/ru/Home.md
Labels: Doc

#490 Added option for extracting default templates of qif and deb packages
  Deploy/Distributions/deb.cpp
  Deploy/Distributions/qif.cpp
  Deploy/Distributions/ziparhive.cpp
  Deploy/configparser.cpp
  Deploy/configparser.h
  Deploy/deploy.cpp
  Deploy/deploycore.cpp
  Deploy/deploycore.h
  Deploy/extracter.cpp
  Deploy/packing.cpp
  Deploy/packing.h
  UnitTests/tst_deploytest.cpp
  docs/en/ExtractDefaultsTemplates.md
  docs/en/Home.md
  docs/en/Options.md
  docs/ru/ExtractDefaultsTemplates.md
  docs/ru/Home.md
  docs/ru/Options.md
Labels: Enhancement

#493 Fix #396 "add stdc++ lib into ignore list"
  Deploy/configparser.cpp
Labels: Bug, Linux

#498 Build error fix
  Deploy/metafilemanager.cpp
Labels: Bug

#501 fix recursive moving
  Deploy/Deploy.pro
  Deploy/configparser.cpp
  Deploy/configparser.h
  Deploy/deployconfig.cpp
  Deploy/deployconfig.h
  Deploy/filemanager.cpp
  Deploy/targetdata.cpp
  Deploy/targetdata.h
Labels: Bug

#500 Added variable CQT_PKG_ROOT for applications.
  Deploy/configparser.cpp
  Deploy/configparser.h
  Deploy/extracter.cpp
  Deploy/metafilemanager.cpp
  UnitTests/testRes/TestQMLWidgets.sh
  UnitTests/tst_deploytest.cpp
Labels: Enhancement, Linux, Windows

#505 Fix deploy platforms plugins for non executable targets.
  Deploy/Deploy.pro
  Deploy/configparser.cpp
  Deploy/dependenciesscanner.cpp
  Deploy/dependenciesscanner.h
  Deploy/deploy.cpp
  Deploy/elf_type.cpp
  Deploy/extracter.cpp
  Deploy/extracter.h
  Deploy/generalfiles_type.cpp
  Deploy/generalfiles_type.h
  UnitTests/tst_deploytest.cpp
Labels: Bug, Linux

#506 v1.5.0.19 Alpha
  Deploy/Deploy.pro
  Deploy/configparser.cpp
  Deploy/dependenciesscanner.cpp
  Deploy/dependenciesscanner.h
  Deploy/deploy.cpp
  Deploy/elf_type.cpp
  Deploy/extracter.cpp
  Deploy/extracter.h
  Deploy/generalfiles_type.cpp
  Deploy/generalfiles_type.h
  QIFData/config/configLinux.xml
  QIFData/config/configWin.xml
  QIFData/packages/cqtdeployer.1_5/meta/package.xml
  UnitTests/tst_deploytest.cpp
  snap/gui/cqtdeployer.desktop
  snap/snapcraft.yaml
Labels: Bug, Linux

#507 Fix of a windows launcher
  Deploy/Distributions/idistribution.cpp
  Deploy/metafilemanager.cpp
  UnitTests/tst_deploytest.cpp
Labels: Bug, Windows

#509 Hide cmd on windows.
  Deploy/metafilemanager.cpp
  UnitTests/tst_deploytest.cpp
Labels: Bug, Windows
