Repository QuasarApp/CQtDeployer, pull requests merged in 2021-02, with the labels that each got.

#512 V1.5
  test.pri
Labels: Bug, Windows

#514 Added more logs into packing step
  Deploy/Distributions/idistribution.cpp
  Deploy/deploy.h
  Deploy/packing.cpp
Labels: Bug, Linux, Windows

#515 Added new envirement variable CQT_RUN_FILE
  Deploy/metafilemanager.cpp
  UnitTests/testRes/TestQMLWidgets.sh
  docs/en/EnvironmentVariables.md
  docs/ru/EnvironmentVariables.md
Labels: Enhancement, Linux, Windows

#516 V1.5.0.22 alpha
  Deploy/Deploy.pro
  Deploy/Distributions/idistribution.cpp
  Deploy/deploy.h
  Deploy/metafilemanager.cpp
  Deploy/packing.cpp
  QIFData/config/configLinux.xml
  QIFData/config/configWin.xml
  QIFData/packages/cqtdeployer.1_5/meta/package.xml
  UnitTests/testRes/TestQMLWidgets.sh
  docs/en/EnvironmentVariables.md
  docs/ru/EnvironmentVariables.md
  snap/gui/cqtdeployer.desktop
  snap/snapcraft.yaml
Labels: Doc, Enhancement, Linux, Windows

#518 v1.5.0.23 alpha
  Deploy/Deploy.pro
  Deploy/metafilemanager.cpp
  QIFData/config/configLinux.xml
  QIFData/config/configWin.xml
  QIFData/packages/cqtdeployer.1_5/meta/package.xml
  snap/gui/cqtdeployer.desktop
  snap/snapcraft.yaml
Labels: Bug

#522 Use QString::SkipEmptyParts in Qt 5.13.x or earlier and Qt::SkipEmptyParts in Qt 5.14.0 or later
  Deploy/defines.h
  Deploy/filemanager.cpp
Labels: Bug, Linux, Windows

#523 Task 396
  Deploy/deploycore.cpp
  Deploy/deploycore.h
  Deploy/extra.cpp
  Deploy/extracter.cpp
  Deploy/extracter.h
  Deploy/metafilemanager.cpp
  Deploy/packing.cpp
  UnitTests/testRes/TestQMLWidgets.sh
  UnitTests/tst_deploytest.cpp
Labels: Enhancement, Windows

#526 Allow testing on still supported versions and completely disable it on older versions
  CQtDeployer.pro
  test.pri
Labels: BuildSystem

#528 Semantically separate the two irrelevant tests in testSystemLib
  UnitTests/tst_deploytest.cpp
Labels: Bug, Linux, Windows

#529 Added support of the control custom translation files.
  Deploy/configparser.cpp
  Deploy/deployconfig.cpp
  Deploy/deployconfig.h
  Deploy/deploycore.cpp
  Deploy/distromodule.cpp
  Deploy/distromodule.h
  Deploy/extracter.cpp
  Deploy/extracter.h
  UnitTests/res.qrc
  UnitTests/testRes/TestTr.qm
  UnitTests/tst_deploytest.cpp
  docs/en/Options.md
  docs/ru/Options.md
Labels: Enhancement

#537 Update guide
  docs/en/Guide.md
  docs/ru/Guide.md
Labels: Doc

#538 Fixes after updating of the guide.
  docs/en/Guide.md
  docs/ru/Guide.md
Labels: Bug, Doc

#541 Add credits text and banner in readme
  README.md
  res/Credits.jpg
Labels: Doc

#543 Remove russian text in readme
  README.md
Labels: Doc

#521 Fix documentation for bin and extraLibs options
  Deploy/deploycore.cpp
  docs/en/Options.md
  docs/ru/Options.md
Labels: Doc
