Repository QuasarApp/CQtDeployer, pull requests merged in 2021-06, with the labels that each got.

#616 Documentation correction
  Deploy/deploycore.h
  md/en/Build-and-Install.md
  md/en/Changelog.md
  md/en/ExtraFiles.md
  md/en/ExtractDefaultsTemplates.md
  md/en/Guide.md
  md/en/Options.md
  md/ru/Changelog.md
  md/ru/DisableShortcats.md
  md/ru/ExtraFiles.md
  md/ru/ExtractDefaultsTemplates.md
  md/ru/Guide.md
  md/ru/Options.md
Labels: documentation

#623 Docs correction
  README.md
  doxygen.conf
  md/README.md
  md/en/1_4.md
  md/en/1_5.md
  md/en/Build-and-Install.md
  md/en/Changelog.md
  md/en/CompareFeatures.md
  md/en/DEB.md
  md/en/DeployConfigFile.md
  md/en/Description.md
  md/en/DisableShortcats.md
  md/en/EnvironmentVariables.md
  md/en/ExtraFiles.md
  md/en/ExtractDefaultsTemplates.md
  md/en/Guide.md
  md/en/Options.md
  md/en/Packing.md
  md/en/QIF.md
  md/en/QuickGuide.md
  md/en/ReleaseReviews.md
  md/en/ZIP.md
  md/ru/1_4.md
  md/ru/1_5.md
  md/ru/Build-and-Install.md
  md/ru/Changelog.md
  md/ru/CompareFeatures.md
  md/ru/DEB.md
  md/ru/DeployConfigFile.md
  md/ru/Description.md
  md/ru/DisableShortcats.md
  md/ru/EnvironmentVariables.md
  md/ru/ExtraFiles.md
  md/ru/ExtractDefaultsTemplates.md
  md/ru/Guide.md
  md/ru/Options.md
  md/ru/Packing.md
  md/ru/QIF.md
  md/ru/QuickGuide.md
  md/ru/ReleaseReviews.md
  md/ru/ZIP.md
Labels: documentation

#624 Added ssl libs into Qt 3rdparty libraries
  Deploy/deploycore.cpp
Labels: Enhancement, Linux, Windows

#626 Fix of documentation about disabling of an automation creating shortcuts
  md/en/DisableShortcats.md
  md/en/Options.md
  md/ru/DisableShortcats.md
  md/ru/Options.md
Labels: Bug, documentation

#625 Added qifOut option
  Deploy/Distributions/qif.cpp
  Deploy/deploycore.cpp
  UnitTests/tst_deploytest.cpp
  md/en/Options.md
  md/ru/Options.md
Labels: Enhancement, Linux, Windows

#631 Fix of the generation of the packages shortcuts
  Deploy/targetinfo.cpp
Labels: Bug

#633 Fix custom script warning
  Deploy/metafilemanager.cpp
Labels: Bug
