Repository QuasarApp/CQtDeployer, pull requests merged in 2021-07, with the labels that each got.

#634 Added support prefixes for extra data
  Deploy/configparser.cpp
  Deploy/configparser.h
  Deploy/deploycore.cpp
  Deploy/deploycore.h
  Deploy/extracter.cpp
Labels: Bug

#637 ru changelog update
  md/ru/Changelog.md
Labels: documentation

#638 Ffx the getDefaultTemplate option
  Deploy/configparser.cpp
  Deploy/configparser.h
  UnitTests/tst_deploytest.cpp
  md/en/DEB.md
  md/en/QIF.md
  md/ru/DEB.md
  md/ru/QIF.md
Labels: Bug, documentation

#639 Fix documentation about creating qifw package
  md/en/QIF.md
  md/ru/QIF.md
Labels: documentation

#641 Fix warning on installer
  QIFData/packages/cqtdeployer.1_5/meta/installscript.js
Labels: Bug

#645 Added warning for the libDir option
  md/en/Options.md
  md/ru/Options.md
Labels: documentation

#646 Fix conflict between libDir and targetDir options
  Deploy/configparser.cpp
  Deploy/configparser.h
  Deploy/envirement.cpp
  Deploy/envirement.h
  UnitTests/tst_deploytest.cpp
Labels: Bug
