Repository QuasarApp/CQtDeployer, pull requests merged in 2021-04, with the labels that each got.

#563 Change qr code
  README.md
  res/qr.png
Labels: documentation

#566 Fix links in docs
  docs/en/DEB.md
  docs/en/Options.md
  docs/en/Packing.md
  docs/en/QIF.md
  docs/en/ReleaseReviews.md
  docs/en/ZIP.md
  docs/ru/DEB.md
  docs/ru/Options.md
  docs/ru/Packing.md
  docs/ru/QIF.md
  docs/ru/ReleaseReviews.md
  docs/ru/ZIP.md
Labels: documentation

#569 Fix of getting default template.
  Deploy/Distributions/deb.cpp
  Deploy/Distributions/deb.h
  Deploy/Distributions/defaultdistro.cpp
  Deploy/Distributions/defaultdistro.h
  Deploy/Distributions/idistribution.cpp
  Deploy/Distributions/idistribution.h
  Deploy/Distributions/qif.cpp
  Deploy/Distributions/qif.h
  Deploy/Distributions/ziparhive.cpp
  Deploy/Distributions/ziparhive.h
  Deploy/filemanager.cpp
  Deploy/packing.cpp
  UnitTests/tst_deploytest.cpp
  docs/en/DisableShortcats.md
  docs/en/Home.md
  docs/en/Packing.md
  docs/ru/DisableShortcats.md
  docs/ru/Home.md
  docs/ru/Packing.md
Labels: Bug

#572 Readme update
  README.md
Labels: documentation

#576 Use call method in bat files for console applications
  Deploy/dependenciesscanner.cpp
  Deploy/dependenciesscanner.h
  Deploy/deploycore.cpp
  Deploy/deploycore.h
  Deploy/elf_type.cpp
  Deploy/extracter.cpp
  Deploy/extracter.h
  Deploy/generalfiles_type.cpp
  Deploy/libinfo.cpp
  Deploy/libinfo.h
  Deploy/metafilemanager.cpp
  Deploy/metafilemanager.h
  Deploy/pe_type.cpp
  UnitTests/modulesqt5152.cpp
  UnitTests/testutils.cpp
  UnitTests/testutils.h
  UnitTests/tst_deploytest.cpp
Labels: Bug, Windows

#578 Fixed mispells
  Deploy/configparser.cpp
  Deploy/dependenciesscanner.cpp
  Deploy/deploycore.cpp
Labels: Bug
